import type {
  GeneratePromoScriptsInput,
  GenerateSceneBreakdownInput,
  TextAnalysisProvider,
  TTSProvider,
} from './providers';
import type { PromoScene, PromoScriptVersion } from './models';
import { countArabicWords, createId, estimateArabicVoiceoverDurationSec } from './utils';

const teaserQuestions = ['فكيف تغيّر المسار؟', 'وكيف صارت القرارات نقطة تحوّل؟', 'وهل كانت النتائج حتمية؟', 'وماذا لو كُشف ما بقي في الظل؟'];

function toneLabel(tone: GeneratePromoScriptsInput['tone']): string {
  return {
    political_teaser: 'سياسي مشحون',
    historical_serious: 'تاريخي جاد',
    investigative: 'تحقيقي متصاعد',
    emotional_dramatic: 'درامي إنساني',
  }[tone];
}

function buildScript(input: GeneratePromoScriptsInput, index: number): string {
  const sourceLead = input.sourceScript.trim().split(/[.!؟\n]/).find(Boolean)?.trim() || input.title;
  const openings = [
    `في ${input.title}، تبدأ الحكاية من لحظة بدت عابرة، لكنها فتحت بابًا لتداعيات أكبر.`,
    `لم تكن القصة مجرد حدث في الذاكرة، بل سلسلة قرارات غيّرت معنى ما بعدها.`,
    `خلف العنوان المعروف، تختبئ تفاصيل صنعت نتيجة لم يكن أحد يتوقعها.`,
  ];
  return [
    openings[index % openings.length],
    `من ${sourceLead.slice(0, 90)}... تتشكل أسئلة لا يمكن تجاهلها.`,
    teaserQuestions[index % teaserQuestions.length],
    teaserQuestions[(index + 1) % teaserQuestions.length],
    `في هذا البرومو نقترب من الخيط الأول، ونترك الوعد كاملًا للفيلم الوثائقي.`,
    `النبرة: ${toneLabel(input.tone)}.`,
  ].join(' ');
}

function promptPackage(scene: number, visualIntent: string, aspectRatio: '16:9' | '9:16') {
  return {
    shortPrompt: `Cinematic documentary visual for scene ${scene}: ${visualIntent}`,
    detailedPrompt: `Create a symbolic cinematic documentary shot for scene ${scene}. Use documents, maps, silhouettes, shadows, archival-inspired motion graphics, and restrained dramatic lighting. Avoid fabricating real events beyond the supplied documentary script.`,
    negativePrompt: 'No visible text, no logos, no watermarks, no deepfake, no misleading fake archival footage, no distorted faces or hands.',
    suggestedDurationSec: 6,
    cameraMovement: 'Slow push-in with subtle parallax',
    suggestedAspectRatio: aspectRatio,
    disclosureRequired: true,
  } as const;
}

export const mockTextAnalysisProvider: TextAnalysisProvider = {
  id: 'mock-text',
  async analyzeScript(input) {
    return {
      summary: input.sourceScript.trim().slice(0, 240) || 'No script provided yet.',
      factualBoundaries: ['Use only facts from the supplied documentary script.', 'Treat generated visuals as illustrative, not archival proof.'],
    };
  },
  async extractPromoAngles() {
    return ['القرار الذي غيّر المسار', 'السؤال الذي بقي بلا إجابة', 'النتيجة التي صنعت ذاكرة الفيلم'];
  },
  async generatePromoScripts(input) {
    return [0, 1, 2].map((index): PromoScriptVersion => {
      const text = buildScript(input, index);
      return {
        id: createId('script'),
        label: `خيار ${index + 1}`,
        text,
        wordCount: countArabicWords(text),
        estimatedDurationSec: estimateArabicVoiceoverDurationSec(text),
        selected: index === 0,
      };
    });
  },
  async generateSceneBreakdown(input: GenerateSceneBreakdownInput) {
    const chunks = input.selectedScript
      .split(/(?<=[.؟!])\s+/)
      .map((part) => part.trim())
      .filter(Boolean);
    const sceneCount = input.durationSec >= 60 ? 9 : 6;
    const duration = Math.round((input.durationSec / sceneCount) * 10) / 10;

    return Array.from({ length: sceneCount }, (_, index): PromoScene => {
      const voiceoverText = chunks[index % chunks.length] || `مشهد وثائقي تشويقي رقم ${index + 1}.`;
      const visualIntent = index === 0
        ? 'Opening shock with title atmosphere'
        : index === sceneCount - 1
          ? 'Final promise and documentary title reveal'
          : 'Escalating documentary question with symbolic evidence';
      return {
        id: createId('scene'),
        sceneNumber: index + 1,
        startSec: Math.round(index * duration * 10) / 10,
        durationSec: index === sceneCount - 1 ? Math.max(1, input.durationSec - Math.round(index * duration * 10) / 10) : duration,
        voiceoverText,
        visualIntent,
        suggestedSourceFootage: 'اختر لقطة من الفيلم تدعم المعنى دون كشف الذروة.',
        assetType: index === 0 || index === sceneCount - 1 ? 'title_card' : 'film_clip',
        imagePrompt: promptPackage(index + 1, visualIntent, '16:9'),
        videoPrompt: promptPackage(index + 1, visualIntent, '16:9'),
        textOverlay: index === sceneCount - 1 ? input.title : teaserQuestions[index % teaserQuestions.length],
        textPreset: index === sceneCount - 1 ? 'final_title_card' : 'big_center_question',
        notes: 'Generated by mock provider. Edit before export.',
        approved: false,
      };
    });
  },
};

export const mockTtsProvider: TTSProvider = {
  id: 'mock-tts',
  async listVoices() {
    return [{ id: 'mock-ar-doc', name: 'Mock Arabic Documentary', language: 'ar' }];
  },
  async estimateDuration(input) {
    return {
      words: countArabicWords(input.text),
      durationMs: Math.round(estimateArabicVoiceoverDurationSec(input.text) * 1000),
    };
  },
  async synthesizeVoiceover() {
    throw new Error('Mock TTS estimates duration only. Import a voiceover or configure a real provider.');
  },
};
